# Generated by Django 5.0.1 on 2024-12-15 13:31

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=50)),
                ('monetary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('category', models.CharField(choices=[('organisation/charity/npo/pbo', 'Organisation/Charity/NPO/PBO'), ('in loving memory of', 'In Loving Memory Of'), ('fire/drought/disaster/support', 'Fire/Drought/Disaster/Support'), ('education & training', 'Education & Training'), ('sport', 'sport'), ('Social welfare/commnity development/support', 'Social Welfare/Commnity Development/Support'), ('youth', 'youth'), ('arts & culture', 'Arts & Culture'), ('Nature conservation', 'Nature Conservation'), ('Animal Welfare/outreach', 'Animal Welfare/Outreach'), ('Vehicle', 'Vehicle'), ('Home', 'Home'), ('Business/App', 'Business/App'), ('legal', 'Legal'), ('Other', 'Other')], max_length=100)),
                ('story', models.TextField()),
                ('event', models.CharField(choices=[('aQuelle Midmar Mile 2025', 'aQuelle Midmar Mile 2025'), ('Hyrox johannesburg|Season 24/25', 'Hyrox johannesburg|Season 24/25'), ('vusa24', 'vusa24'), ('Comrades 2024', 'Comrades 2024'), ('WESEEYOU EVENT', 'WESEEYOU EVENT'), ('AMASHOVA DURBA CLASSIC', 'AMASHOVA DURBA CLASSIC'), ('IRONMAN 70.3 -2024', 'IRONMAN 70.3 -2024'), ('ANNUAL KIDS CHRISTMAS PARTY', 'ANNUAL KIDS CHRISTMAS PARTY'), ('aQuelle Midmar Mile 2025', 'aQuelle Midmar Mile 2025')], max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(upload_to='images/')),
                ('video_url', models.URLField(max_length=1000)),
                ('social_link', models.URLField(max_length=1000)),
                ('address1', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('organization_payment', models.BooleanField(default=False)),
                ('single_payment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
