# Generated by Django 5.0.1 on 2024-12-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
