# Generated by Django 5.0.1 on 2024-12-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_campaign_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='sector',
            field=models.CharField(choices=[('child welfare', 'Child Welfare'), ('education', 'Education'), ('Community development', 'Community Development'), ('Environmental', 'Environmental'), ('Health', 'Health'), ('medical', 'Medical')], max_length=100, null=True),
        ),
    ]
