# Generated by Django 5.0.1 on 2024-12-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_campaign_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
