# Generated by Django 5.0.1 on 2024-12-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_profile_campaign_campaign_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='goal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
