# Generated by Django 5.0.1 on 2025-01-02 13:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_campaign_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
