# Generated by Django 5.0.1 on 2025-01-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_campaign_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='uuid',
        ),
    ]
