# Generated by Django 5.0.1 on 2025-01-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_campaign_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='token',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
