# Generated by Django 5.0.1 on 2025-01-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_campaign_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='token',
            field=models.CharField(blank=True, default='pofZD5K2zasihcNNYrjeXrvR0BmgLG85', max_length=32, unique=True),
        ),
    ]
