# Generated by Django 5.0.1 on 2025-01-02 15:40

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_campaign_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='token',
            field=models.CharField(blank=True, default=base.models.generate_unique_token, max_length=32, unique=True),
        ),
    ]
