# Generated by Django 5.0.1 on 2025-01-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_campaign_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_launch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_status',
            field=models.BooleanField(default=False),
        ),
    ]
