# Generated by Django 5.0.1 on 2025-01-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_campaign_is_launch_campaign_is_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
