# Generated by Django 5.0.1 on 2025-01-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_paymentdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='country',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
