# Generated by Django 5.0.1 on 2025-01-07 14:43

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_campaign_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
