# Generated by Django 5.0.1 on 2025-01-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_campaign_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
